# Site settings
title: nomcha
email: tasty@nomcha.com
description: > # this means to ignore newlines in this block
   a concise blog of tasty teas.
url: https://nomcha.com

#removing any of this will omit the relevant HTML
#to add more SVGs, see: http://codepen.io/ruandre/pen/howFi
twitter_username: nomcha_blog
instagram_username: nomcha_blog

timezone: America/Los_Angeles
encoding: utf-8

gems:
     - jekyll-sitemap
     - jekyll-feed

exclude: [TODO.txt, Gemfile*]
permalink:
   /:categories/:title/